language: R
sudo: false
cache: packages

env: ISOLATED_REDIS=true

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: hiredis
      latex: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libhiredis-dev
      - redis-server

services:
  - redis-server

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
