# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heartbeat_start <- function(host, port, key, value, period, expire) {
    invisible(.Call('RedisHeartbeat_heartbeat_start', PACKAGE = 'RedisHeartbeat', host, port, key, value, period, expire))
}

heartbeat_stop <- function() {
    invisible(.Call('RedisHeartbeat_heartbeat_stop', PACKAGE = 'RedisHeartbeat'))
}

heartbeat_status <- function() {
    .Call('RedisHeartbeat_heartbeat_status', PACKAGE = 'RedisHeartbeat')
}

heartbeat_key <- function() {
    .Call('RedisHeartbeat_heartbeat_key', PACKAGE = 'RedisHeartbeat')
}

heartbeat_signal_key <- function(key) {
    .Call('RedisHeartbeat_heartbeat_signal_key', PACKAGE = 'RedisHeartbeat', key)
}

heartbeat_cleanup <- function(host, port, key) {
    invisible(.Call('RedisHeartbeat_heartbeat_cleanup', PACKAGE = 'RedisHeartbeat', host, port, key))
}

