# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

keep_alive_start <- function(host, port, key, timeout, expire) {
    invisible(.Call('RedisKeepAlive_keep_alive_start', PACKAGE = 'RedisKeepAlive', host, port, key, timeout, expire))
}

keep_alive_stop <- function() {
    invisible(.Call('RedisKeepAlive_keep_alive_stop', PACKAGE = 'RedisKeepAlive'))
}

keep_alive_status <- function() {
    .Call('RedisKeepAlive_keep_alive_status', PACKAGE = 'RedisKeepAlive')
}

keep_alive_key <- function() {
    .Call('RedisKeepAlive_keep_alive_key', PACKAGE = 'RedisKeepAlive')
}

